# Set colors
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

# Set reload key to r
bind r source-file ~/.tmux.conf
bind K kill-window

# Start windows and panes at 0, not 1
set -g base-index 0
setw -g pane-base-index 0

set -g history-limit 30000

# Use vim bindings
setw -g mode-keys vi

# Remap window navigation to vim
unbind-key j
bind-key j select-pane -D
unbind-key k
bind-key k select-pane -U
unbind-key h
bind-key h select-pane -L
unbind-key l
bind-key l select-pane -R

# Set the title bar
set -g set-titles on
#set -g set-titles-string '#(whoami) :: #h :: #(curl ipecho.net/plain;echo)'
set -g set-titles-string '#(whoami) :: #h: '

# Set status bar
set -g status-bg black
set -g status-fg white
set -g status-interval 5
set -g status-left-length 90
set -g status-right-length 60
set -g status-left "#[fg=Green]#(whoami)#[fg=white]::#[fg=blue]#(hostname -s)#[fg=white]:: "
set -g status-justify left
set -g status-right '#(tmux-mem-cpu-load) :: #[fg=Cyan]#S #[fg=white]%a %d %b %R'
# https://github.com/neovim/neovim/wiki/FAQ
set -sg escape-time 10

# Fix pbcopy/pbpaste on macOS
if-shell "[ $(uname) = 'Darwin' ]" {
    # Last windows fix
    bind-key C-b last-window

    # brew install reattach-to-user-namespace
    set-option -g default-command "reattach-to-user-namespace -l zsh"
}

# From https://unix.stackexchange.com/questions/318281/how-to-copy-and-paste-with-a-mouse-with-tmux
# Drag form lower right up to left.
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -T copy-mode-vi    C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-vi    C-WheelDownPane send-keys -X halfpage-down
bind -T copy-mode-emacs C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-emacs C-WheelDownPane send-keys -X halfpage-down
bind-key m set-option -g mouse on \; display 'Mouse: ON'
bind-key M set-option -g mouse off \; display 'Mouse: OFF'

# To copy, left click and drag to highlight text in yellow,
# once you release left click yellow text will disappear and will automatically be available in clibboard
# Use vim keybindings in copy mode
setw -g mode-keys vi
# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

set-option -g focus-events on

if-shell "test -f /home/linuxbrew/.linuxbrew/bin/zsh" {
    set-option -g default-shell /home/linuxbrew/.linuxbrew/bin/zsh
}
if-shell "test -f /bin/zsh && ! test -f /opt/homebrew/bin/zsh && ! test -f /home/linuxbrew/.linuxbrew/bin/zsh" {
    set-option -g default-shell /bin/zsh
}
if-shell "test -f /bin/bash && ! test -f /bin/zsh && ! test -f /opt/homebrew/bin/zsh && ! test -f /home/linuxbrew/.linuxbrew/bin/zsh" {
    set-option -g default-shell /bin/bash
}

# Don't rename windows
set-option -g allow-rename off
