new-session -s standard -n shell
split-window -h
selectp -t 0
clock-mode
split-window -v
resize-pane -L 25
new-window -n vim -c ~/Documents/workspace
new-window -n zsh
new-window -n zsh
new-window -n zsh
selectp -t 0
resize-pane -D 10
new-window -n zsh
select-window -t 0
